# Generated by Django 5.2 on 2025-05-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_request_payment_status_request_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
