# Generated by Django 5.2 on 2025-04-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_customuser_latitude_alter_customuser_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='vendoruser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cost_per_km',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='DeliveryUser',
        ),
        migrations.DeleteModel(
            name='VendorUser',
        ),
    ]
