# Generated by Django 5.2 on 2025-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_userpayment_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='stripe_price_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
