# Generated by Django 5.2 on 2025-04-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_userpayment_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='stripe_price_id',
        ),
    ]
