# Generated by Django 5.2 on 2025-04-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_product_stripe_price_id'),
        ('payment', '0004_remove_userpayment_stripe_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.product')),
            ],
        ),
    ]
