# Generated by Django 5.2 on 2025-04-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Explore our wide selection of products in this category'),
        ),
    ]
