# Generated by Django 5.2 on 2025-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
