# Generated by Django 5.2 on 2025-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_product_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_good',
            field=models.BooleanField(default=False),
        ),
    ]
