# Generated by Django 5.2 on 2025-04-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_product_is_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_good',
        ),
    ]
